print("")
print("           AAAA            LL                BBBBBBBBBB")
print("          AAAAA            LL                BBBBBBBBBB")
print("         AA   AA           LL                BB      BB")
print("         AA   AA           LL                BB      BB")
print("        AAAAAAAAA          LL                BBBBBBBBBBBB")
print("        AAAAAAAAA          LL                BBBBBBBBBBBB")
print("       AA       AA         LL                BB        BB")
print("       AA       AA         LL                BB        BB")
print("      AA         AA   ..   LLLLLLLLLLLL  ..  BBBBBBBBBBBB  ..")
print("      AA         AA   ..   LLLLLLLLLLLL  ..  BBBBBBBBBBBB  ..")
print("")
